### ISSUE TITLE
After the last update, products do not load into category pages.

### ISSUE THREAD

**Issue by marcofrasson** [UraraReika/jwb-products-grid-load-more#1]
Hi! After the last update, products do not load into category pages.

BUG Category: https://devloja.goflow.digital/c/moveis/

Shop Page OK: https://devloja.goflow.digital/produtos/

Another thing is that the quantity field is not taking the value of the field when adding. Before loading the infinite scroll, it works if I put more than two units in the field. Then it doesn't work and add 1 in 1 regardless of the value that is in the quantity field.

**Comment by UraraReika** [comment]
Hello @marcofrasson !

You mean [this](https://github.com/UraraReika/jwb-products-grid-load-more/commit/2eb1da283f59192268071a9e4522d3e50f7825b2) update?

**Comment by marcofrasson** [comment]
@UraraReika yes!

**Comment by UraraReika** [comment]
@marcofrasson try to update and check
