### ISSUE TITLE
Problem with pagination

### ISSUE THREAD

**Issue by petrovui** [UraraReika/jwb-products-grid-load-more#2]
Plugin must cowork with Pagination widget.  Then "Load More" button is pressed and second page of products is loaded in Product Grid the pagination widget must switch to second page etc.

**Comment by petrovui** [comment]
You can see how it must work here (on bitrix):
http://wpcleaner.space/catalog/travy_i_ozdorovitelnye_sbory/

**Comment by UraraReika** [comment]
Done in last update.
