### ISSUE TITLE
Hide "Load more" button then all objects are loaded

### ISSUE THREAD

**Issue by petrovui** [UraraReika/jwb-products-grid-load-more#3]
Load More widget must have function to hide himself then all products was loaded in Product Grid etc.

**Comment by UraraReika** [comment]
This functionality already complete. Please download plugin ones more with latest improvements.

**Comment by petrovui** [comment]
Sorry, but it's not. I got latest version (1.1.0) and you can see it here https://ruherbs.bio/shop/product-category/travy-i-ozdorovitelnye-sbory/

**Comment by UraraReika** [comment]
Perhaps this is related to your site. Please contact our [support team](https://support.crocoblock.com/support/home/). Thank you!
