### ISSUE TITLE
Causes critical error

### ISSUE THREAD

**Issue by webcoreinc** [UraraReika/jwb-products-grid-load-more#4]
Crashed my site with a critical error.
<img width="689" alt="Screenshot 2023-01-23 at 6 50 52 PM" src="https://user-images.githubusercontent.com/99219613/214177953-9e8fc1a1-36ad-445f-a619-f9ee8980f288.png">

**Comment by UraraReika** [comment]
Hello @webcoreinc! Thanks for the feedback.

Right now we in the middle of testing process after refactoring this plugin. But you can fell free and download it from dev branch. This will fix all the existing in your site errors. Soon this version will be available in the main branch.

Thank you for your understanding.
