### ISSUE TITLE
Crashed site

### ISSUE THREAD

**Issue by webcoreinc** [UraraReika/jwb-products-grid-load-more#6]
Your plugin crashed another site and we nearly missed a launch deadline.

What is you paypal so i can send you a money request for what we had to pay to fix you terrible coding?

Proof in image
<img width="689" alt="load-more-bug" src="https://user-images.githubusercontent.com/99219613/214581383-0b340d97-7ce7-4b2f-9ec9-b7da13b8b997.png">

**Comment by UraraReika** [comment]
Hello @webcoreinc! 

As i said to you in previous issues version of this plugin in main branch does'n work with latest JetWooBuilder plugin and need some modifications. This modification were made in dev branch of this repo then tested and now it is safe and ready to use. Soon this two branches will be merged. Looking at your screenshot I cat tell for sure that you use incompatible version.

Thank you for your understanding.

**Comment by webcoreinc** [comment]
I am not using premium addons which has a product grid with built in load more. I don't trust this plugin or crocoblock 

When we get critical error from plugin, we trash it.

I would take this offline and refine your coding skills. Just advice from a 20 year developer,.
