### ISSUE TITLE
Issue in my site with this plugin.. please help

### ISSUE THREAD

**Issue by Meyertron** [UraraReika/jwb-products-grid-load-more#7]
Se ha producido un error del tipo E_ERROR en la línea 67 del archivo /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/jwb-products-grid-load-more-main/includes/pglm-load-more-integration.php. Mensaje de error: Uncaught Error: Call to a member function get() on array in /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/jwb-products-grid-load-more-main/includes/pglm-load-more-integration.php:67
Stack trace:
#0 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(308): pglm_get_widget_attributes('', Array, Array, Object(Jet_Woo_Products_Grid_Shortcode))
#1 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#2 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/jet-woo-builder/templates/widgets/global/products-grid/loop-start.php(23): apply_filters('jet-woo-builder...', '', Array, Array, Object(Jet_Woo_Products_Grid_Shortcode))
#3 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/jet-woo-builder/includes/shortcodes/traits/products-shortcode.php(342): include('/home4/oilqgkmy...')
#4 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/jet-woo-builder/includes/shortcodes/base.php(209): Jet_Woo_Products_Grid_Shortcode->_shortcode(NULL)
#5 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/jet-woo-builder/includes/widgets/global/jet-woo-products.php(2361): Jet_Woo_Builder_Shortcode_Base->do_shortcode(Array)
#6 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/base/controls-stack.php(2268): Elementor\Jet_Woo_Products->render()
#7 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#8 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base->render_content()
#9 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Widget_Base->get_raw_data(true)
#10 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/base/element-base.php(536): Elementor\Element_Base->get_raw_data(true)
#11 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/core/base/document.php(966): Elementor\Element_Base->get_raw_data(true)
#12 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/core/base/document.php(632): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#13 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/base/controls-stack.php(1021): Elementor\Core\Base\Document->get_initial_config()
#14 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/core/editor/editor.php(383): Elementor\Controls_Stack->get_config()
#15 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->enqueue_scripts('')
#16 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...')
#19 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#20 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#21 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#22 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/general-template.php(3043): do_action('wp_head')
#23 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#24 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/core/editor/editor-loader.php(113): include('/home4/oilqgkmy...')
#25 /home4/oilqgkmy/public_html/ferreonline-cl/wp-content/plugins/elementor/core/editor/editor.php(172): Elementor\Core\Editor\Editor_Loader->print_root_template()
#26 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->init('')
#27 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#28 /home4/oilqgkmy/public_html/ferreonline-cl/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#29 /home4/oilqgkmy/public_html/ferreonline-cl/wp-admin/admin.php(419): do_action('admin_action_el...')
#30 /home4/oilqgkmy/public_html/ferreonline-cl/wp-admin/post.php(12): require_once('/home4/oilqgkmy...')
#31 {main}
  thrown

**Comment by UraraReika** [comment]
Hello @Meyertron and thanks for the feedback.

This plugin has undergone major updates and we advise you to update it. Simply download the latest version from main branch.

**Comment by Meyertron** [comment]
Can you please tell me where I can download it from? Thank you very much for answering

**Comment by UraraReika** [comment]
Here - https://github.com/UraraReika/jwb-products-grid-load-more, like this https://tppr.me/MZfdi. Just keep the plugins folder name the same as before. You can although contact support team so they can help you  https://support.crocoblock.com/support/home/
